Library-Management-Website-Project00-main/WebLibrary/WebLibrary/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('student.urls')),
    path("", include('book.urls')),
    path('', include('userprofile.urls')),
]

Library-Management-Website-Project00-main/WebLibrary/book/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('tabrules/',views.tabrules, name='tabrules'),
    path('introduce/',views.introduce, name='introduce'),
    path('booklib/', views.booklib, name="booklib"),
    path('category_detail/<int:pk>/', views.category_detail, name='category_detail'),
    path('book_detail/<int:pk>/', views.book_detail, name='book_detail'),
    path('author_detail/<int:pk>/', views.author_detail, name='author_detail'),
    path('author/', views.author, name="author"),
    
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

Library-Management-Website-Project00-main/WebLibrary/student/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.home, name ='home'),
    path('home1/', views.homefanpage, name='homefanpage'),
    path('login/', views.loginPage, name="login"),
    path('logout/', views.signout, name='logout'),
    path('register/', views.register, name='register'),
    path('forgot/', views.forgot, name="forgot"),
    path('confirm/', views.confirm, name="confirm"),
    path('reset/<str:token>/', views.reset, name="reset"),
    path('success/', views.success, name="success"),
    path('profile/', views.profile, name="profile"),
    path('editprofile/', views.edit_profile, name="editprofile")
]

Library-Management-Website-Project00-main/WebLibrary/student/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class OTP(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    token = models.CharField(max_length=6)
    created_at = models.DateTimeField(auto_now_add=True)

class Student(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    def __str__(self):
        return self.user.username

Library-Management-Website-Project00-main/WebLibrary/userprofile/models.py
from django.db import models
from django.contrib.auth.models import User
#from multiupload.fields import MultiFileField
# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    desc = models.CharField( max_length=200, blank=True)
    profile_img = models.ImageField(default='media/avatar.jpg', upload_to='media', blank=True)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

Library-Management-Website-Project00-main/WebLibrary/student/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms.models import ModelForm
from django.forms.widgets import FileInput
from .models import Student

class RegistrationForm(forms.Form):
    first_name = forms.CharField(max_length=20)
    last_name = forms.CharField(max_length=20)
    student_id = forms.IntegerField()
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput, min_length=8, max_length=16)
    confirm_password = forms.CharField(widget=forms.PasswordInput)

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        confirm_password = cleaned_data.get('confirm_password')

        if password and confirm_password and password != confirm_password:
            raise ValidationError('Passwords do not match')
 
class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

class StudentForm(ModelForm):
    class Meta:
        model = Student
        fields = '__all__'

Library-Management-Website-Project00-main/WebLibrary/student/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required, user_passes_test
from django.core.mail import send_mail
from .models import OTP
from .forms import LoginForm
import random
from django.contrib.auth import get_user_model
from django.contrib.auth.tokens import default_token_generator
from django.utils.http import urlsafe_base64_decode
from django.urls import reverse
from userprofile.views import profile, edit_profile
from category.models import Category

def home(request):
    categories = Category.objects.all()
    print(categories)
    context = {
        'latest_categories': categories,
    }
    return render(request, 'student/home.html', context)

def homefanpage(request):
    categories = Category.objects.all()
    print(categories)
    context = {
        'latest_categories': categories,
    }
    return render(request, 'student/homefanpage.html', context)

@user_passes_test(lambda u: not u.is_authenticated, login_url='homefanpage')
def loginPage(request):
    categories = Category.objects.all()
    print(categories)
    context = {
        'latest_categories': categories,
    }
    if request.method == "POST":
        form = LoginForm(request.POST)  
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]

            user = authenticate(request, username=username, password=password)

            if user is not None:
                login(request, user)
                return redirect('homefanpage') 
            else:
                form.add_error(None, "Bạn đã nhập sai tài khoản hoặc mật khẩu")
                messages.error(request, "Xin vui lòng nhập lại")

    else:
        form = LoginForm()

    context['form'] = form

    return render(request, "student/Login.html", context)

def register(request):
    if request.method == 'POST':
        firstName = request.POST.get('firstName')
        lastName = request.POST.get('lastName')  
        studentID = request.POST.get('studentID')  
        email = request.POST.get('email')
        password = request.POST.get('password')
        confirmPassword = request.POST.get('confirmPassword')

        # Tạo từ điển tróng
        error_messages = {}

        # Kiểm tra các trường dữ liệu để tìm ra dữ liệu đang bỏ trống
        if not firstName:
            error_messages['firstName'] = "None"
        if not lastName:
            error_messages['lastName'] = "None"
        if not studentID:
            error_messages['studentID'] = "None"
        if not email:
            error_messages['email'] = "None"
        if not password:
            error_messages['password'] = "None"
        if not confirmPassword:
            error_messages['confirmPassword'] = "None"

        # Kiểm tra Student ID và email xem đã tồn tại chưa
        if User.objects.filter(username=studentID).exists():
            error_messages['studentID_exists'] = "Student ID đã tồn tại!"

        if User.objects.filter(email=email).exists():
            error_messages['email_exists'] = "Email đã tồn tại!"

        # Kiểm tra định dạng email
        if not email.endswith('@st.vju.ac.vn'):
            error_messages['invalid_email'] = "'@st.vju.ac.vn'"
        
        email_prefix = email.split('@')[0]
        if email_prefix != studentID:
            error_messages['email_prefix_mismatch'] = "Đầu email phải giống với Student ID"

        # Kiểm tra kích thước mật khẩu
        if not 8 <= len(password) <=16:
            if len(password) < 8:
                error_messages['password_length_min'] = "Mật khẩu tối thiểu 8 ký tự"
            elif len(password) > 16:
                error_messages['password_length_max'] = "Mật khẩu tối đa 16 ký tự"
                


        # Kiểm tra mật khẩu có khớp không
        if password != confirmPassword:
            error_messages['password_mismatch'] = "Mật khẩu không khớp!"

        # Quay lại trang đăng ký nếu xảy ra lỗi và hiển thị lỗi
        if error_messages:
            return render(request, 'student/register.html', {'error_messages':  error_messages, 'input_data': request.POST})


        # Tạo người dùng mới
        new_user = User.objects.create_user(username=studentID, email=email, password=password)
        new_user.first_name = firstName
        new_user.last_name = lastName
        new_user.save()

        # Thông báo thành công và chuyển hướng
        messages.success(request, "Đăng ký thành công.")
        return redirect('login')
    
    categories = Category.objects.all()
    print(categories)
    context = {
        'latest_categories': categories,
    }

    return render(request, 'student/register.html', context)

def signout(request):
    logout(request)
    return redirect('/')

def forgot(request):
    if request.method == "POST":
        firstName = request.POST.get('firstName')
        lastName = request.POST.get('lastName')
        email = request.POST.get("email")
        username = request.POST.get("username")
        
        # Kiểm tra xem username và email đã được nhập hay chưa
        if not username:
            messages.error(request, "Tên người dùng không được bỏ trống.")
            return redirect("forgot")

        if not email:
            messages.error(request, "Email không được bỏ trống.")
            return redirect("forgot")

        try:
            user = User.objects.get(username=username, email=email)
            otp = str(random.randint(100000, 999999))
            OTP.objects.create(user=user, token=otp)
            subject = "Tài khoản của bạn sẽ được đổi mật khẩu khi bạn nhập OTP"
            message = f"Chào bạn {username} thân mến,\n\nChúng tôi rất vui mừng thông báo về một sự kiện đặc biệt trên tài khoản của bạn tại Thư viện VJULIB.\n\nĐể đảm bảo an toàn và bảo mật cho bạn, chúng tôi đã gửi một Mã OTP đặc biệt. Hãy nhập mã này sau khi bạn đăng nhập:\n\nMã OTP: {otp}\n\nNếu đây không phải là bạn, xin đừng lo lắng. Bạn có thể bỏ qua thông báo này hoặc liên hệ ngay với chúng tôi. Chúng tôi sẵn sàng hỗ trợ bạn ngay lập tức và giải đáp mọi thắc mắc.\n\nChúng tôi xin gửi lời cảm ơn sâu sắc nhất đến bạn vì đã tin tưởng và lựa chọn sử dụng dịch vụ của Thư viện VJULIB.\n\nNếu có bất kỳ câu hỏi hoặc nhu cầu hỗ trợ nào khác, Đội Ngũ VJULIB luôn sẵn lòng để giúp đỡ bạn.\n\nTrân trọng,\nĐội Ngũ VJULIB"
            from_email = 'vjulib@gmail.com'
            recipient_list = [email]
            send_mail(subject, message, from_email, recipient_list)
            return redirect("confirm")
        except User.DoesNotExist:
            messages.error(request, "Không tìm thấy tài khoản với thông tin bạn nhập.")
            return redirect("forgot")
    categories = Category.objects.all()
    print(categories)
    context = {
        'latest_categories': categories,
    }
    return render(request, "student/ForgotPassword.html", context)

def confirm(request):
    if request.method == "POST":
        otp = request.POST.get("otp")
        try:
            reset_request = OTP.objects.get(token=otp)
            if reset_request.token == otp:
                return redirect('reset', token=reset_request.token)
            else:
                messages.error(request, "Mã OTP không hợp lệ.")
        except OTP.DoesNotExist:
            messages.error(request, "Mã OTP không hợp lệ.")
    
    categories = Category.objects.all()
    print(categories)
    context = {
        'latest_categories': categories,
    }
    return render(request, 'student/ConfirmForgotPassword.html', context)


def reset(request, token):
    categories = Category.objects.all()
    print(categories)
    context={}
    try:
        OTP_user = OTP.objects.filter(token = token).first()

        if request.method == "POST":
            new_password = request.POST.get("new_password")
            confirm_password = request.POST.get("confirm_password")
            user_id = request.POST.get("user_id")
            
            if user_id is None:
                messages.error(request, "Không tìm thấy thông tin người dùng")
                return redirect('reset', token=token)
            if new_password != confirm_password:
                messages.error(request, "Xin vui lòng nhập lại")
                return redirect('reset', token=token)
            
            # Kiểm tra kích thước mật khẩu
            if not 8 <= len(new_password) <= 16:
                if len(new_password) < 8:
                    messages.error(request, "Mật khẩu tối thiểu 8 ký tự")
                elif len(new_password) > 16:
                    messages.error(request, "Mật khẩu tối đa 16 ký tự")
                return redirect('reset', token=token)
        
            User_obj = User.objects.get(id=user_id)
            User_obj.set_password(new_password)
            User_obj.save()
            return redirect('success')
        context = {
            'user_id': OTP_user.user.id,
            'latest_categories': categories,
            }
    except Exception as e:
        print(e)
    return render(request, 'student/ResetPassword.html', context)

def success(request):
    categories = Category.objects.all()
    print(categories)
    context = {
        'latest_categories': categories,
    }
    return render(request, 'student/succsesforgotpassword.html', context)

Library-Management-Website-Project00-main/WebLibrary/templates/student/ConfirmForgotPassword.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static  %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'student/bootstrap.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'student/styles22.css' %}">
    <link rel="icon" href="{% static 'images/logo/logo.png' %}">
    <title>Xác Nhận Lấy Lại Mật Khẩu</title>

  
</head>
<body class="p-3 m-0 border-0 bd-example m-0 border-0 font-farmily01 ">
  <nav class="navbar navbar-expand-lg ">
    <div class="container-fluid">
      <h2 class="navbar-brand ms-5 font-weight01"> <a class="no-underline" style="color: black;" href="/">VJULIB</a></h2>

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav offset-4 mb-2 mb-lg-0 font-weight01 " style="margin-left: 26.005% !important;">

          <li class="nav-item">
            <a class="nav-link active " aria-current="page" href="/">Trang Chủ</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="/introduce/">Giới Thiệu</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="/tabrules/">Nội Quy</a>
          </li>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Thể loại sách
            </a>
            <ul class="dropdown-menu" style="max-height: 170px !important; overflow-y: auto;">
              {% for category in latest_categories|dictsort:"title" %}
              <li>
                <a class="dropdown-item" href="/login/">
                  {{ category.title }}
                </a>
              </li>
              {% endfor %}
            </ul>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="/login/">Tác Giả</a>
          </li>
        </ul>
      </div>
    </div>
</nav>

      <div class="container">
        <div class="container">
          <div class="row flex-column flex-md-row">
            <div class="mt-5 col-6 col-md-6">
              <div> 
                <h3 class="font-weight01">Quên Mật Khẩu? Đổi Mật Khẩu</h3>
                <h5 class="font-weight03">Vui lòng nhập Email và Mã sinh viên bạn dùng để đăng kí tài khoản,
                  chúng tôi sẽ gửi mã OTP vào địa chỉ Email!</h5>
                <br>
                <p class="font-weight03">Vui lòng đọc thông tin dưới đây và sau đó vui lòng chia sẻ thông tin được yêu cầu.</p>  
                <ul class="font-weight03">
                  <li>Không tiết lộ mật khẩu của bạn cho bất cứ ai.</li>
                  <li>Không sử dụng lại mật khẩu.</li>
                  <li>Sử dụng mật khẩu chứa cả chữ và số.</li>
                  <li>ID đăng nhập của bạn. ID Student là mã sinh viên định danh của bạn.</li>
                </ul>
            </div>
            </div>
              
              <div class="container col-6 col-md-6 mt-5">
                  <div class="col-md-6 offset-md-3 ">
                      <div class="card shadow custom-card-width">
                          <div class="card-body text-center" style="background-color: #FFFBFB;" >
                            <form method="post" action="{% url 'confirm' %}">
                              {% csrf_token %}
                              {% for message in messages %}
                                <div class="fontcolor">{{message}}</div>
                              {% endfor %} 
                              <h6 class="font-weight04">Thay đổi Mật Khẩu</h6>
                              <p class="font-weight01">Xác Nhận Thay Đổi Mật Khẩu Với ID: <span>{{ request.user.stundent_id }}</span></p>
                              <p class="font-weight01">Vui Lòng Kiểm Tra Email</p>

                              <input class="form-control mb-3 shadow-sm" name="otp" type="number" placeholder="OTP">
                              <button type="submit" class="btn btn-primary mt-3 mb-5 offset-5 shadow">
                                <a style="color:white; text-decoration:none; " href="/reset/">
                                  <span class="font-weight03">
                                    Tiếp tục
                                  </span>
                                </a>
                              </button>
                            </form>
                          </div>
                      </div>
                  </div>
              </div>
      </div>

      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>   
</body>
</html>

Library-Management-Website-Project00-main/WebLibrary/templates/student/EditProfile.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'student/bootstrap.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'student/styles33.css' %}">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    <link rel="icon" href="{% static 'images/logo/logo.png' %}">
    <title>Cài Đặt & Quyền Riêng Tư</title>
  
</head>
<body class="font-farmily01" style="background-color: #fff ;">
  <nav class="navbar navbar-expand-lg ">
      <div class="container-fluid">
        <h2 class="navbar-brand ms-5 font-weight01"> <a class="no-underline" style="color: black;" href="/booklib/">VJULIB</a></h2>
  
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
  
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav offset-4 mb-2 mb-lg-0 font-weight01 ">
  
            <li class="nav-item">
              <a class="nav-link active " aria-current="page" href="/booklib/">Trang Chủ</a>
            </li>
  
            <li class="nav-item">
              <a class="nav-link" href="/introduce/">Giới Thiệu</a>
            </li>
  
            <li class="nav-item">
              <a class="nav-link" href="/tabrules/">Nội Quy</a>
            </li>
  
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Thể loại sách
              </a>
              <ul class="dropdown-menu" style="max-height: 170px !important; overflow-y: auto;">
                {% for category in latest_categories|dictsort:"title" %}
                <li>
                  <a class="dropdown-item" href="{% url 'category_detail' pk=category.pk %}">
                    {{ category.title }}
                  </a>
                </li>
                {% endfor %}
              </ul>
            </li>

            <li class="nav-item">
              <a class="nav-link" href="/author/">Tác Giả</a>
            </li>
          </ul>
          
        </div>
        
      </div>
      <form class="d-flex" role="search">
            {% csrf_token %}
            <li class="nav-item dropdown list-unstyled btn-group">
              <p class=" font-weight03" style="margin-right: 5px; width: 150px; margin-top: 15px;">{{request.user.first_name}} {{request.user.last_name}}</p>
              <a class="profile-content nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                <img src="{{ user.profile.profile_img.url }}" alt="..." style="border-radius: 25px; width: 30px; height: 30px; object-fit: cover; margin-right:-5px">
              </a>
              <ul class="dropdown-menu dropdown-menu-end" style="font-family: 'Montserrat' ">
                
                <li>
                  <a class="dropdown-item " href="/profile/">
                    <i class='bx bxs-user-circle' style="font-size: 30px; position: relative; top: 7px; color: #1C1E21;"></i>
                    <span style="font-weight: 500;">Trang cá nhân</span>
                    <span style=" width: 10px; height: 10px;border: solid #333; border-width: 0 2px 2px 0; display: inline-block; transform: rotate(-45deg); margin-left: 5px; margin-left: 5.25rem;">
                    </span>
                  </a>
                </li>
  
                <li>
                  <a class="dropdown-item " href="/editprofile/">
                    <i class='bx bx-cog' style="font-size: 30px; position: relative; top: 7px; color: #1C1E21;"></i> 
                    <span style="font-weight: 500;">Cài đặt & quyền riêng tư </span>
                    <span style=" width: 10px; height: 10px;border: solid #333; border-width: 0 2px 2px 0; display: inline-block; transform: rotate(-45deg); margin-left: 5px;">
                    </span>
                  </a>
                </li>
                
                <li>
                  <a class="dropdown-item" href="/logout/">
                    <i class='bx bx-log-out bx-flip-horizontal' style="font-size: 30px; position: relative; top: 7px; color: #1C1E21;"></i>
                    <span style="font-weight: 500;">Đăng xuất</span>
                  </a>
                </li>
              </ul>
            </li>
          </form> 
  </nav>

  <div style="margin-top: 5rem !important;">
      <div class=" col-md-8 mx-auto">
        <form method="post" enctype="multipart/form-data">
          <div class="d-flex flex-column align-items-center justify-content-center position-relative">
            {% csrf_token %}
                <img id="preview_image" src="{{ user.profile.profile_img.url }}" alt="User Image" class="img-fit rounded-circle small-avatar" style="width: 100px; height: 100px;">
            <label class="text-center position-relative">
                <label class="bx bxs-camera position-absolute top-0 end-0" style="cursor: pointer; transform: translate(160%, -100%); font-size: 24px;">
                    <span style="position: absolute; clip: rect(0, 0, 0, 0); pointer-events: none;">
                      <input type="file" id="id_profile_img" name="profile_img" value="{{user.profile.profile_img.url}}" style="display: none;" onchange="readURL(this);">
                    </span>
                </label>
            </label>
        </div>
        
        <br>
            <div class="d-flex justify-content-center">
              {% csrf_token %}
              <div class="mb-3">
              <label for="id_first_name"><input type="text" name="first_name" value="{% if request.user.first_name %}{{request.user.first_name}}{% endif %}" placeholder="Điền họ" style="width: 150px; height: 45px; background-color: #d7d7d7;" class="form-control"></label>
              </div>
              <div class="mb-3 ms-1" style="width: 150px; height: 45px;">
                  <label for="id_last_name"><input type="text" name="last_name" value="{% if request.user.last_name %}{{request.user.last_name}}{% endif %}" placeholder="Điền tên" style="width: 150px; height: 45px; background-color: #d7d7d7;" class="form-control"></label>
              </div>
            </div>
            <div class="d-flex justify-content-center">
              <label for="id_desc"><input type="text" name="desc" value="{% if user.profile.desc %}{{user.profile.desc}}{% endif %}" placeholder="Hãy giới thiệu về bản thân mình thêm nhé!" style="width: 300px; height: 45px; background-color: #d7d7d7;" class="form-control"></label>
            </div>
            <div class="d-flex justify-content-center">
              <button type="submit" class="mt-2 btn btn-primary" style="width: 150px; height: 45px;">Cập Nhật</button>
              <button class="mt-2 btn btn-danger ms-1" style="width: 150px; height: 45px; background-color: red;"><a href="/forgot/" class="mt-2" style="color: white; text-decoration: none;">Đổi Mật Khẩu</a></button>
            </div>
            <br>
            <div class="d-flex justify-content-center">
            {% if form.errors %}
              <div class="fontcolor">
                  <p>Vui lòng nhập đầy đủ họ và tên!</p>
              </div>
            {% endif %}
            </div>
        </form>
  </div>
  
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  <script>
        $(document).ready(function () {
          function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    $('#preview_image').attr('src', e.target.result);
                };
                reader.readAsDataURL(input.files[0]);
            }
        }
    
            // Đảm bảo sự kiện change được gọi khi trang đã sẵn sàng
            $("#id_profile_img").on('change', function () {
                readURL(this);
            });
        });
  </script>  

</body>
</html>